name: guessita
version: '2.1.4'
summary: python library extractor
description: |
    GuessIt is a python library that extracts as much information as possible from a video filename.
grade: stable

confinement:strict

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: python
